# Generated by Django 2.2.2 on 2019-07-01 10:30
# fmt: off

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.SmallIntegerField(help_text='user path', unique=True, verbose_name='external id')),
                ('internal_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, verbose_name='internal data')),
                ('external_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, verbose_name='external data')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='is enabled')),
                ('position', models.SmallIntegerField(default=0, verbose_name='position')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ('position',),
            },
        ),
    ]
